language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - TYPO3_VERSION=^6.2 COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=^7.6 COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0

matrix:
  exclude:
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
      php: 5.5
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0
      php: 5.6
  include:
    - php: 5.5
      env: TYPO3_VERSION=^6.2 COVERAGE=0 FUNCTIONAL=1
    - php: 5.5
      env: TYPO3_VERSION=^7.6 COVERAGE=1 FUNCTIONAL=1
    - php: 7.0
      env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=1
  allow_failures:
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=1
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  # Removes xdebug to speed up tests
  - phpenv config-rm xdebug.ini
  # Installs TYPO3
  - composer require typo3/cms=$TYPO3_VERSION;
  # If TYPO3_VERSION is NOT 6.2.x
  - >
    if [[ "$TYPO3_VERSION" != "^6.2" ]]; then
      export "TYPO3_PATH_WEB"=$PWD/.Build/Web;
    else
      export "TYPO3_PATH_WEB"=$PWD;
    fi
  # Restore composer.json
  - git checkout composer.json;
  # Locating UnitTests.xml
  - export "UNIT_XML"=`find . -name 'UnitTests.xml' -type f`
  # Location FunctionalTests.xml
  - export "FUNCTIONAL_XML"=`find . -name 'FunctionalTests.xml' -type f`

script:
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      ./bin/phpunit --colors -c -c $UNIT_XML Tests/Unit/*
    fi
    echo;
